const GET_ALL_VEHICLES_START = "GET_ALL_VEHICLES_START";
const GET_ALL_VEHICLES_SUCCESS = "GET_ALL_VEHICLES_SUCCESS";
const GET_ALL_VEHICLES_FAILURE = "GET_ALL_VEHICLES_FAILURE";

const ADD_VEHICLE_START = "ADD_VEHICLE_START";
const ADD_VEHICLE_SUCCESS = "ADD_VEHICLE_SUCCESS";

const DELETE_VEHICLE_START = "DELETE_VEHICLE_START";
const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS";

const UPDATE_VEHICLE_START = "UPDATE_VEHICLE_START";
const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS";

const VEHICLE_ACTION_FAILURE = "VEHICLE_ACTION_FAILURE";

const vehiclesActionTypes = {
  GET_ALL_VEHICLES_START,
  GET_ALL_VEHICLES_SUCCESS,
  GET_ALL_VEHICLES_FAILURE,
  ADD_VEHICLE_START,
  ADD_VEHICLE_SUCCESS,
  DELETE_VEHICLE_START,
  DELETE_VEHICLE_SUCCESS,
  UPDATE_VEHICLE_START,
  UPDATE_VEHICLE_SUCCESS,
  VEHICLE_ACTION_FAILURE
};

export default vehiclesActionTypes;
